In [1]:
#Wilson Song
#Assignment 6


#libraries

import math
import numpy as np
import numpy.linalg as la
import scipy.linalg as sla



In [2]:

#setup
#Matrix A
A = np.array([[1.,0.,1.],[2.,1.,2.],[1.,0.,-1.]])
print ('\nA =\n',A)
print ('\nShape of A = ',np.shape(A))
n = np.shape(A)[0]
print ('\nDimensionality of A = ',n)

At = np.transpose(A)
print ('\nAt =\n',At)
print ('\nShape of At = ',np.shape(At))


#column Vector
B = np.array([2.,0.,7.])
B = B.reshape(3,1)
print ('\nB = \n',B)
print ('\nShape of B = ',np.shape(B))




A =
 [[ 1.  0.  1.]
 [ 2.  1.  2.]
 [ 1.  0. -1.]]

Shape of A =  (3, 3)

Dimensionality of A =  3

At =
 [[ 1.  2.  1.]
 [ 0.  1.  0.]
 [ 1.  2. -1.]]

Shape of At =  (3, 3)

B = 
 [[2.]
 [0.]
 [7.]]

Shape of B =  (3, 1)


In [3]:
# 1  - Calculate A^-1
invA = la.inv(A)

#2 - print A and A^-1

print ('\nA =\n',A)
print ('\nA^-1 =\n',invA)



A =
 [[ 1.  0.  1.]
 [ 2.  1.  2.]
 [ 1.  0. -1.]]

A^-1 =
 [[ 0.5  0.   0.5]
 [-2.   1.  -0. ]
 [ 0.5 -0.  -0.5]]


In [4]:
#3 - calculate and print AA-1 and A^-1A

print ('\nA * A^-1 =\n',np.matmul(A , invA))
print ('\nA^-1 * A =\n',np.matmul(invA , A))


A * A^-1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A^-1 * A =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


When we multiply the Matrix by its inverse, we epect to get the identity matrix which as shown above is true.

In [38]:
#4 - Calculate the L0, L1, L2, and Linf vector norms of B
print('\nVector norm L0 of B  = \n', la.norm(B))
print('\nVector norm L1 of B  = \n', la.norm(B,1))
print('\nVector norm L2 of B  = \n', la.norm(B,2))
print('\nVector norm Linf of B  = \n', la.norm(B,np.inf))


Vector norm L0 of B  = 
 7.280109889280518

Vector norm L1 of B  = 
 9.0

Vector norm L2 of B  = 
 7.280109889280519

Vector norm Linf of B  = 
 7.0


In [39]:
#5 - Calculate the L0, L1, L2, and Linf vector norms of A
print('\nVector norm L1 of A  = \n', la.norm(A,1))
print('\nVector norm L2 of A  = \n', la.norm(A,2))
print('\nVector norm Linf of A  = \n', la.norm(A,np.inf))


Vector norm L1 of A  = 
 4.0

Vector norm L2 of A  = 
 3.2886278151179287

Vector norm Linf of A  = 
 5.0


In [6]:
#6 - Calculate and print det(A), det(A^-1), det(A)det(A^-1)

det_A=la.det(A)
det_invA=la.det(invA)

print('\nDeterminant of A = \n', det_A)
print('\nDeterminant of A^-1 = \n', det_invA)
print('\ndet(A)*det(A^-1) = \n',det_A*det_invA)


Determinant of A = 
 -2.0

Determinant of A^-1 = 
 -0.5

Det(A)*det(A^-1) = 
 1.0


In [8]:
#7 - Solve the system of equations AX=B
#8 - Print A,X,and B

x_result=la.solve(A,B)
print('\nA =\n',A)
print('\nB = \n',B)
print('\nX = \n',x_result)


A =
 [[ 1.  0.  1.]
 [ 2.  1.  2.]
 [ 1.  0. -1.]]

B = 
 [[2.]
 [0.]
 [7.]]

X = 
 [[ 4.5]
 [-4. ]
 [-2.5]]


In [10]:
#9 - Compare AX and B
AX = np.matmul(A,x_result)

print('\nAX = \n',AX)
print('\nB = \n',B)
print('\nDifference between AX and B = \n',AX-B)



AX = 
 [[2.]
 [0.]
 [7.]]

B = 
 [[2.]
 [0.]
 [7.]]

Difference between AX and B = 
 [[0.]
 [0.]
 [0.]]


We expect to get AX=B which is indeed what we get here.

In [15]:
#10 - Calculate and print the eigenvalues and eigenvectors of A
eigen_values,eigen_vector = la.eig(A)
print('\nEigenvalues of A = \n',eigen_values)
print('\nEigenvectors of A = \n',eigen_vector)


Eigenvalues of A = 
 [ 1.          1.41421356 -1.41421356]

Eigenvectors of A = 
 [[ 0.          0.14464074 -0.34919364]
 [ 1.          0.98766876 -0.4091058 ]
 [ 0.          0.05991216  0.84302802]]


In [53]:
#11 - Show that A*eigenvector=eigenvalues*eigenvector
eigenvalue_0=np.array([1])
eigenvalue_1=np.array([1.41421356])
eigenvalue_2=np.array([-1.41421356])

eigenvector_0=np.array([0,1,0])
eigenvector_0=eigenvector_0.reshape(3,1)

eigenvector_1=np.array([0.14464074, 0.98766876, 0.98766876])
eigenvector_2=eigenvector_0.reshape(3,1)

eigenvector_1=np.array([-0.34919364,-0.4091058,0.84302802])
eigenvector_2=eigenvector_0.reshape(3,1)

print('\nMatrix A * Eigenvector(i=0) = \n',A*eigenvector_0)
print('\nEigenvalues(i=0) * Eigenvector(i=0) = \n',eigenvalue_0*eigenvector_0)
print('\nMatrix A * Eigenvector(i=1) = \n',A*eigenvector_1)
print('\nEigenvalues(i=1) * Eigenvector(i=1) = \n',eigenvalue_1*eigenvector_1)
print('\nMatrix A * Eigenvector(i=2) = \n',A*eigenvector_2)
print('\nEigenvalues(i=2) * Eigenvector(i=2) = \n',eigenvalue_2*eigenvector_2)


Matrix A * Eigenvector(i=0) = 
 [[ 0.  0.  0.]
 [ 2.  1.  2.]
 [ 0.  0. -0.]]

Eigenvalues(i=0) * Eigenvector(i=0) = 
 [[0]
 [1]
 [0]]

Matrix A * Eigenvector(i=1) = 
 [[-0.34919364 -0.          0.84302802]
 [-0.69838728 -0.4091058   1.68605604]
 [-0.34919364 -0.         -0.84302802]]

Eigenvalues(i=1) * Eigenvector(i=1) = 
 [-0.49383438 -0.57856297  1.19222166]

Matrix A * Eigenvector(i=2) = 
 [[ 0.  0.  0.]
 [ 2.  1.  2.]
 [ 0.  0. -0.]]

Eigenvalues(i=2) * Eigenvector(i=2) = 
 [[-0.        ]
 [-1.41421356]
 [-0.        ]]


In [56]:
#12 - Calculate and print the spectral radius of A.

#spectral radius of a matrix is the maximum of the modulus of its eigenvalues
spectral_radius = max(abs(eigen_values))
print("\nSpectral Radius of Matrix A =\n",spectral_radius)


Spectral Radius of Matrix A =
 1.4142135623730951


In [31]:
#13 - Detemine the LU decomposition of A such that A=PLU 
#14 - Print A,P,L,U

P,L,U=sla.lu(A)
print('\nP = \n',P)
print('\nL = \n',L)
print('\nU = \n',U)
PL= np.matmul(P,L)
PLU=np.matmul(PL,U)
print ('\nA =\n',A)
print ('\nPLU =\n',PLU)


P = 
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

L = 
 [[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 1.  1. ]]

U = 
 [[ 2.   1.   2. ]
 [ 0.  -0.5  0. ]
 [ 0.   0.  -2. ]]

A =
 [[ 1.  0.  1.]
 [ 2.  1.  2.]
 [ 1.  0. -1.]]

PLU =
 [[ 1.  0.  1.]
 [ 2.  1.  2.]
 [ 1.  0. -1.]]


P represents the permutation matrix
L represents the lower triangular matrix and
U represents the upper traignular marix
We expect to get A=PLU which is true.